/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecruiterDemoRouteImport } from './routes/recruiter.demo'
import { Route as AuthenticatedRecruiterRouteRouteImport } from './routes/_authenticated/recruiter/route'
import { Route as AuthenticatedCandidateRouteRouteImport } from './routes/_authenticated/candidate/route'
import { Route as AuthenticatedCandidateIndexRouteImport } from './routes/_authenticated/candidate/index'
import { Route as AuthenticatedCandidateResumesIndexRouteImport } from './routes/_authenticated/candidate/resumes/index'
import { Route as AuthenticatedCandidateProfileIndexRouteImport } from './routes/_authenticated/candidate/profile/index'
import { Route as AuthenticatedCandidateLearningIndexRouteImport } from './routes/_authenticated/candidate/learning/index'
import { Route as AuthenticatedCandidateJobsIndexRouteImport } from './routes/_authenticated/candidate/jobs/index'
import { Route as AuthenticatedCandidateInterviewsIndexRouteImport } from './routes/_authenticated/candidate/interviews/index'
import { Route as AuthenticatedCandidateResumesIdRouteImport } from './routes/_authenticated/candidate/resumes/$id'
import { Route as AuthenticatedCandidateInterviewsIdRouteImport } from './routes/_authenticated/candidate/interviews/$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterDemoRoute = RecruiterDemoRouteImport.update({
  id: '/recruiter/demo',
  path: '/recruiter/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRecruiterRouteRoute =
  AuthenticatedRecruiterRouteRouteImport.update({
    id: '/recruiter',
    path: '/recruiter',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCandidateRouteRoute =
  AuthenticatedCandidateRouteRouteImport.update({
    id: '/candidate',
    path: '/candidate',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCandidateIndexRoute =
  AuthenticatedCandidateIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCandidateRouteRoute,
  } as any)
const AuthenticatedCandidateResumesIndexRoute =
  AuthenticatedCandidateResumesIndexRouteImport.update({
    id: '/resumes/',
    path: '/resumes/',
    getParentRoute: () => AuthenticatedCandidateRouteRoute,
  } as any)
const AuthenticatedCandidateProfileIndexRoute =
  AuthenticatedCandidateProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedCandidateRouteRoute,
  } as any)
const AuthenticatedCandidateLearningIndexRoute =
  AuthenticatedCandidateLearningIndexRouteImport.update({
    id: '/learning/',
    path: '/learning/',
    getParentRoute: () => AuthenticatedCandidateRouteRoute,
  } as any)
const AuthenticatedCandidateJobsIndexRoute =
  AuthenticatedCandidateJobsIndexRouteImport.update({
    id: '/jobs/',
    path: '/jobs/',
    getParentRoute: () => AuthenticatedCandidateRouteRoute,
  } as any)
const AuthenticatedCandidateInterviewsIndexRoute =
  AuthenticatedCandidateInterviewsIndexRouteImport.update({
    id: '/interviews/',
    path: '/interviews/',
    getParentRoute: () => AuthenticatedCandidateRouteRoute,
  } as any)
const AuthenticatedCandidateResumesIdRoute =
  AuthenticatedCandidateResumesIdRouteImport.update({
    id: '/resumes/$id',
    path: '/resumes/$id',
    getParentRoute: () => AuthenticatedCandidateRouteRoute,
  } as any)
const AuthenticatedCandidateInterviewsIdRoute =
  AuthenticatedCandidateInterviewsIdRouteImport.update({
    id: '/interviews/$id',
    path: '/interviews/$id',
    getParentRoute: () => AuthenticatedCandidateRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/candidate': typeof AuthenticatedCandidateRouteRouteWithChildren
  '/recruiter': typeof AuthenticatedRecruiterRouteRoute
  '/recruiter/demo': typeof RecruiterDemoRoute
  '/candidate/': typeof AuthenticatedCandidateIndexRoute
  '/candidate/interviews/$id': typeof AuthenticatedCandidateInterviewsIdRoute
  '/candidate/resumes/$id': typeof AuthenticatedCandidateResumesIdRoute
  '/candidate/interviews/': typeof AuthenticatedCandidateInterviewsIndexRoute
  '/candidate/jobs/': typeof AuthenticatedCandidateJobsIndexRoute
  '/candidate/learning/': typeof AuthenticatedCandidateLearningIndexRoute
  '/candidate/profile/': typeof AuthenticatedCandidateProfileIndexRoute
  '/candidate/resumes/': typeof AuthenticatedCandidateResumesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/recruiter': typeof AuthenticatedRecruiterRouteRoute
  '/recruiter/demo': typeof RecruiterDemoRoute
  '/candidate': typeof AuthenticatedCandidateIndexRoute
  '/candidate/interviews/$id': typeof AuthenticatedCandidateInterviewsIdRoute
  '/candidate/resumes/$id': typeof AuthenticatedCandidateResumesIdRoute
  '/candidate/interviews': typeof AuthenticatedCandidateInterviewsIndexRoute
  '/candidate/jobs': typeof AuthenticatedCandidateJobsIndexRoute
  '/candidate/learning': typeof AuthenticatedCandidateLearningIndexRoute
  '/candidate/profile': typeof AuthenticatedCandidateProfileIndexRoute
  '/candidate/resumes': typeof AuthenticatedCandidateResumesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/candidate': typeof AuthenticatedCandidateRouteRouteWithChildren
  '/_authenticated/recruiter': typeof AuthenticatedRecruiterRouteRoute
  '/recruiter/demo': typeof RecruiterDemoRoute
  '/_authenticated/candidate/': typeof AuthenticatedCandidateIndexRoute
  '/_authenticated/candidate/interviews/$id': typeof AuthenticatedCandidateInterviewsIdRoute
  '/_authenticated/candidate/resumes/$id': typeof AuthenticatedCandidateResumesIdRoute
  '/_authenticated/candidate/interviews/': typeof AuthenticatedCandidateInterviewsIndexRoute
  '/_authenticated/candidate/jobs/': typeof AuthenticatedCandidateJobsIndexRoute
  '/_authenticated/candidate/learning/': typeof AuthenticatedCandidateLearningIndexRoute
  '/_authenticated/candidate/profile/': typeof AuthenticatedCandidateProfileIndexRoute
  '/_authenticated/candidate/resumes/': typeof AuthenticatedCandidateResumesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/candidate'
    | '/recruiter'
    | '/recruiter/demo'
    | '/candidate/'
    | '/candidate/interviews/$id'
    | '/candidate/resumes/$id'
    | '/candidate/interviews/'
    | '/candidate/jobs/'
    | '/candidate/learning/'
    | '/candidate/profile/'
    | '/candidate/resumes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/recruiter'
    | '/recruiter/demo'
    | '/candidate'
    | '/candidate/interviews/$id'
    | '/candidate/resumes/$id'
    | '/candidate/interviews'
    | '/candidate/jobs'
    | '/candidate/learning'
    | '/candidate/profile'
    | '/candidate/resumes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/candidate'
    | '/_authenticated/recruiter'
    | '/recruiter/demo'
    | '/_authenticated/candidate/'
    | '/_authenticated/candidate/interviews/$id'
    | '/_authenticated/candidate/resumes/$id'
    | '/_authenticated/candidate/interviews/'
    | '/_authenticated/candidate/jobs/'
    | '/_authenticated/candidate/learning/'
    | '/_authenticated/candidate/profile/'
    | '/_authenticated/candidate/resumes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RecruiterDemoRoute: typeof RecruiterDemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/demo': {
      id: '/recruiter/demo'
      path: '/recruiter/demo'
      fullPath: '/recruiter/demo'
      preLoaderRoute: typeof RecruiterDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/recruiter': {
      id: '/_authenticated/recruiter'
      path: '/recruiter'
      fullPath: '/recruiter'
      preLoaderRoute: typeof AuthenticatedRecruiterRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidate': {
      id: '/_authenticated/candidate'
      path: '/candidate'
      fullPath: '/candidate'
      preLoaderRoute: typeof AuthenticatedCandidateRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidate/': {
      id: '/_authenticated/candidate/'
      path: '/'
      fullPath: '/candidate/'
      preLoaderRoute: typeof AuthenticatedCandidateIndexRouteImport
      parentRoute: typeof AuthenticatedCandidateRouteRoute
    }
    '/_authenticated/candidate/resumes/': {
      id: '/_authenticated/candidate/resumes/'
      path: '/resumes'
      fullPath: '/candidate/resumes/'
      preLoaderRoute: typeof AuthenticatedCandidateResumesIndexRouteImport
      parentRoute: typeof AuthenticatedCandidateRouteRoute
    }
    '/_authenticated/candidate/profile/': {
      id: '/_authenticated/candidate/profile/'
      path: '/profile'
      fullPath: '/candidate/profile/'
      preLoaderRoute: typeof AuthenticatedCandidateProfileIndexRouteImport
      parentRoute: typeof AuthenticatedCandidateRouteRoute
    }
    '/_authenticated/candidate/learning/': {
      id: '/_authenticated/candidate/learning/'
      path: '/learning'
      fullPath: '/candidate/learning/'
      preLoaderRoute: typeof AuthenticatedCandidateLearningIndexRouteImport
      parentRoute: typeof AuthenticatedCandidateRouteRoute
    }
    '/_authenticated/candidate/jobs/': {
      id: '/_authenticated/candidate/jobs/'
      path: '/jobs'
      fullPath: '/candidate/jobs/'
      preLoaderRoute: typeof AuthenticatedCandidateJobsIndexRouteImport
      parentRoute: typeof AuthenticatedCandidateRouteRoute
    }
    '/_authenticated/candidate/interviews/': {
      id: '/_authenticated/candidate/interviews/'
      path: '/interviews'
      fullPath: '/candidate/interviews/'
      preLoaderRoute: typeof AuthenticatedCandidateInterviewsIndexRouteImport
      parentRoute: typeof AuthenticatedCandidateRouteRoute
    }
    '/_authenticated/candidate/resumes/$id': {
      id: '/_authenticated/candidate/resumes/$id'
      path: '/resumes/$id'
      fullPath: '/candidate/resumes/$id'
      preLoaderRoute: typeof AuthenticatedCandidateResumesIdRouteImport
      parentRoute: typeof AuthenticatedCandidateRouteRoute
    }
    '/_authenticated/candidate/interviews/$id': {
      id: '/_authenticated/candidate/interviews/$id'
      path: '/interviews/$id'
      fullPath: '/candidate/interviews/$id'
      preLoaderRoute: typeof AuthenticatedCandidateInterviewsIdRouteImport
      parentRoute: typeof AuthenticatedCandidateRouteRoute
    }
  }
}

interface AuthenticatedCandidateRouteRouteChildren {
  AuthenticatedCandidateIndexRoute: typeof AuthenticatedCandidateIndexRoute
  AuthenticatedCandidateInterviewsIdRoute: typeof AuthenticatedCandidateInterviewsIdRoute
  AuthenticatedCandidateResumesIdRoute: typeof AuthenticatedCandidateResumesIdRoute
  AuthenticatedCandidateInterviewsIndexRoute: typeof AuthenticatedCandidateInterviewsIndexRoute
  AuthenticatedCandidateJobsIndexRoute: typeof AuthenticatedCandidateJobsIndexRoute
  AuthenticatedCandidateLearningIndexRoute: typeof AuthenticatedCandidateLearningIndexRoute
  AuthenticatedCandidateProfileIndexRoute: typeof AuthenticatedCandidateProfileIndexRoute
  AuthenticatedCandidateResumesIndexRoute: typeof AuthenticatedCandidateResumesIndexRoute
}

const AuthenticatedCandidateRouteRouteChildren: AuthenticatedCandidateRouteRouteChildren =
  {
    AuthenticatedCandidateIndexRoute: AuthenticatedCandidateIndexRoute,
    AuthenticatedCandidateInterviewsIdRoute:
      AuthenticatedCandidateInterviewsIdRoute,
    AuthenticatedCandidateResumesIdRoute: AuthenticatedCandidateResumesIdRoute,
    AuthenticatedCandidateInterviewsIndexRoute:
      AuthenticatedCandidateInterviewsIndexRoute,
    AuthenticatedCandidateJobsIndexRoute: AuthenticatedCandidateJobsIndexRoute,
    AuthenticatedCandidateLearningIndexRoute:
      AuthenticatedCandidateLearningIndexRoute,
    AuthenticatedCandidateProfileIndexRoute:
      AuthenticatedCandidateProfileIndexRoute,
    AuthenticatedCandidateResumesIndexRoute:
      AuthenticatedCandidateResumesIndexRoute,
  }

const AuthenticatedCandidateRouteRouteWithChildren =
  AuthenticatedCandidateRouteRoute._addFileChildren(
    AuthenticatedCandidateRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCandidateRouteRoute: typeof AuthenticatedCandidateRouteRouteWithChildren
  AuthenticatedRecruiterRouteRoute: typeof AuthenticatedRecruiterRouteRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCandidateRouteRoute:
    AuthenticatedCandidateRouteRouteWithChildren,
  AuthenticatedRecruiterRouteRoute: AuthenticatedRecruiterRouteRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RecruiterDemoRoute: RecruiterDemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
